# Site settings
title: Chris Laughlin
email: contact@christopherlaughlin.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Rambling of a full stack web application developer, lots of JavaScript and mybe some photos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "//chrislaughlin.github.io" # the base hostname & protocol for your site
twitter_username: chrislaughlin
github_username:  chrislaughlin

# Build settings
markdown: kramdown

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
paginate: 5
future:      true
unpublished: false
